### ISSUE TITLE
Unable to share with background in Instagram Stories

### ISSUE THREAD

**Issue by davizgarzia** [ShekarMudaliyar/social_share#15]
Hi ! @ShekarMudaliyar 

First of all, thank you for this plugin :) 

I tried to use the function to share in Instagram Stories with background but it doesn't works and I don't know what happens. 

Here is my code: 

```
          SocialShare.shareInstagramStorywithBackground(
            file.path,
            "#${bgColor.value.toRadixString(16).substring(2,8)}",
            "#${bgColor.value.toRadixString(16).substring(2,8)}",
            "https://deep-link-url",
            backgroundImagePath: 'bg/bg-1.png'
          );
```

I tried to handle it as a File using [this solution](https://stackoverflow.com/questions/55295593/how-to-convert-asset-image-to-file) but gives me an error too... 

```
          File bg = await getImageFileFromAssets('bg/bg-1.png');
          SocialShare.shareInstagramStorywithBackground(
            file.path,
            "#${bgColor.value.toRadixString(16).substring(2,8)}",
            "#${bgColor.value.toRadixString(16).substring(2,8)}",
            "https://deep-link-url",
            backgroundImagePath: bg.path
          );
```
<img width="784" alt="Captura de pantalla 2020-04-29 a las 21 24 19" src="https://user-images.githubusercontent.com/12697648/80638284-81f48280-8a60-11ea-96db-2ee05e24eb43.png">

I also would want to ask what is the use of the URL parameter ('https://deep-link-url' in the example) :)

Thank you !

**Comment by ShekarMudaliyar** [comment]
I think that error is because that asset cannot be found to be converted to file. Try assigning the same file as the sticker and see if it works.
And url parameter is for deep-links so that if u get approved to have a link in the first place (go though think [link](https://developers.facebook.com/docs/sharing/sharing-to-stories) for more info) the user can click on the sticker to navigate to the app.
